#!/bin/bash

path1='/Users/niko/study/myGithub/ruby/commonDefine.h'
#path1='/Users/niko/work/handday/crmZztx/crmZztx/Classes/Common/commonDefine.h'

path2='/Users/niko/study/myGithub/ruby/constdefined.js'
#path2='/Users/niko/work/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js'

APP_DEBUG=1
APP_TEST=0
JS_DEFINE=LOCATION
TMP_FILE='/tmp/out.tmp.$$'

APP_DEBUG_STRING='#define APP_DEBUG [01]'
APP_TEST_STRING='#define APP_TEST [01]'
JS_DEFINE_STRING="var _type = __getUrlParam('rt') || RunTimeType.*";

case $1 in

dev)
sed "s/$APP_DEBUG_STRING/#define APP_DEBUG $APP_DEBUG/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$APP_TEST_STRING/#define APP_TEST $APP_TEST/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2
;;

test)
APP_DEBUG=0
TEST=1
JS_DEFINE=ONLINE_TEST
sed "s/$APP_DEBUG_STRING/#define APP_DEBUG $APP_DEBUG/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$APP_TEST_STRING/#define APP_TEST $APP_TEST/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2
;;

online)
APP_DEBUG=0
TEST=0
JS_DEFINE=ONLINE
sed "s/$APP_DEBUG_STRING/#define APP_DEBUG $APP_DEBUG/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$APP_TEST_STRING/#define APP_TEST $APP_TEST/g" $path1 > $TMP_FILE && mv $TMP_FILE $path1
sed "s/$JS_DEFINE_STRING/var _type = __getUrlParam('rt') || RunTimeType.$JS_DEFINE;/g" $path2 > $TMP_FILE && mv $TMP_FILE $path2
;;

*)
echo 'Usage: dev|test|online'

;;
esac

exit 0


