#!/bin/bash

case $1 in
start)
$HOME/Library/Tomcat/bin/startup.sh
;;
stop)
$HOME/Library/Tomcat/bin/shutdown.sh
;;
restart)
$HOME/Library/Tomcat/bin/shutdown.sh
$HOME/Library/Tomcat/bin/startup.sh
;;
*)
echo “Usage: start|stop|restart”
;;
esac

exit 0
