#!/bin/bash

sh $HOME/work/workspace/handday/script/zxMerge

exit 0

cp $HOME/work/workspace/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js $HOME/Desktop/constdefined.js

rm -r $HOME/work/workspace/handday/crmZztx/crmZztx/pages

cp -r $HOME/Library/Tomcat/webapps/WebProject/前端项目-v7.0/MobileUI/IOS $HOME/work/workspace/handday/crmZztx/crmZztx/pages

mv $HOME/Desktop/constdefined.js $HOME/work/workspace/handday/crmZztx/crmZztx/pages/resources/js/constdefined.js

echo '......'
echo 'merge is done'
